format_version: 10

pipelines:

  calculator-cicd:
    ...

  calculator-rollback:
    group: defaultGroup

    materials:
      calculator-repo:
        git: https://github.com/Praveenkumar76/calculator.git
        branch: main
        destination: calculator

    stages:
      - Rollback:
          jobs:
            Rollback:
              tasks:
                - exec:
                    working_directory: calculator
                    command: ./scripts/rollback.sh