format_version: 10

pipelines:
  calculator-cicd:
    group: defaultGroup

    materials:
      calculator-repo:
        git: https://github.com/Praveenkumar76/calculator.git
        branch: main
        destination: calculator

    stages:
      - Build:
          jobs:
            Build:
              tasks:
                - exec:
                    working_directory: calculator
                    command: ./scripts/build.sh

              artifacts:
                - build:
                    source: calculator/target/calculator-1.0.0.jar
                    destination: target

      - Docker:
          jobs:
            Docker:
              tasks:
                - fetch:
                    pipeline: calculator-cicd
                    stage: Build
                    job: Build
                    artifact_origin: gocd
                    source: target/calculator-1.0.0.jar
                    destination: calculator/target

                - exec:
                    working_directory: calculator
                    command: ./scripts/docker-build.sh

                - exec:
                    working_directory: calculator
                    command: ./scripts/docker-push.sh

      - Deploy:
          jobs:
            Deploy:
              tasks:
                - exec:
                    working_directory: calculator
                    command: ./scripts/deploy.sh